"use client";

import { useEffect, useMemo, useState } from "react";
import { getRuntimeV3Capabilities } from "../../../lib/runtime-v3-client";
import { listRuntimeUsers, resetRuntimeUserPassword, updateRuntimeUserAdmin, type AdminRuntimeUser } from "../../../lib/admin-runtime-users";
import { useGlymizeLocale } from "../../components/use-glymize-locale";
import styles from "./admin-users.module.css";

export default function AdminUsersPage(){
 const {locale,isRtl}=useGlymizeLocale(),fa=locale==="fa";
 const [enabled,setEnabled]=useState(false),[checked,setChecked]=useState(false),[users,setUsers]=useState<AdminRuntimeUser[]>([]),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState("");
 const [resetUser,setResetUser]=useState<AdminRuntimeUser|null>(null),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState("");
 async function load(){setBusy(true);setError("");try{setUsers(await listRuntimeUsers())}catch(reason){setError(reason instanceof Error?reason.message:"USERS_READ_FAILED")}finally{setBusy(false)}}
 useEffect(()=>{void getRuntimeV3Capabilities().then(c=>{setEnabled(c.adminUsers);if(c.adminUsers)void load()}).finally(()=>setChecked(true))},[]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return users;return users.filter(user=>`${user.firstName} ${user.lastName} ${user.email??""} ${user.mobile??""} ${user.medicalCouncilCode??""}`.toLowerCase().includes(q))},[query,users]);
 const activeCount=users.filter(user=>user.status==="active").length;
 async function toggleStatus(user:AdminRuntimeUser){setBusy(true);setError("");setStatus("");try{await updateRuntimeUserAdmin(user.id,{status:user.status==="active"?"disabled":"active"});setStatus(fa?"وضعیت دسترسی به‌روز شد.":"Access status updated.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"USER_UPDATE_FAILED")}finally{setBusy(false)}}
 async function reset(){if(!resetUser||newPassword.length<10||newPassword!==confirmPassword)return;setBusy(true);setError("");setStatus("");try{await resetRuntimeUserPassword(resetUser.id,newPassword);setStatus(fa?"رمز عبور جدید ثبت شد و نشست‌های قبلی کاربر باید باطل شوند.":"New password saved; existing user sessions should be revoked.");setResetUser(null);setNewPassword("");setConfirmPassword("");await load()}catch(reason){setError(reason instanceof Error?reason.message:"PASSWORD_RESET_FAILED")}finally{setBusy(false)}}
 return <main className={styles.page} dir={isRtl?"rtl":"ltr"}>
  <section className={styles.hero}><div><span>IDENTITY & ACCESS</span><h1>{fa?"کاربران و کنترل دسترسی":"Users & access control"}</h1><p>{fa?"مدیریت حساب پزشکان و اعضای تیم مراقبت؛ غیرفعال‌سازی به‌جای حذف فیزیکی انجام می‌شود تا سابقه audit و handoff بالینی بی‌مرجع نشود.":"Manage physician and care-team accounts. Deactivation is preferred over physical deletion so clinical audit and handoff history remains referentially intact."}</p></div><div className={styles.stat}><b>{activeCount}</b><small>{fa?"حساب فعال":"active accounts"}</small></div></section>
  {!checked?<div className={styles.notice}>{fa?"در حال بررسی سرویس مدیریت کاربران…":"Checking user-management service…"}</div>:!enabled?<div className={styles.notice}>{fa?"طراحی پنل کاربران آماده است، اما این Runtime هنوز قابلیت Admin Users را اعلام نکرده است. تا فعال‌شدن endpointهای امن، هیچ عملیات نمایشی یا حذف صوری ارائه نمی‌شود.":"The user console is ready, but this runtime has not enabled Admin Users yet. No placeholder mutations are exposed until the secure endpoints are active."}</div>:<>
   <div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={fa?"جستجو با نام، کد نظام پزشکی، ایمیل یا موبایل…":"Search by name, Medical Council code, email, or mobile…"}/><button disabled={busy} onClick={()=>void load()}>{fa?"بازخوانی":"Refresh"}</button></div>
   <section className={styles.list}>{visible.map(user=><article className={styles.user} key={user.id}><div className={styles.identity}><span className={styles.avatar}>{user.firstName.slice(0,1)}{user.lastName.slice(0,1)}</span><div><strong>{user.firstName} {user.lastName}</strong><small>{user.role==="physician"?(fa?`پزشک · ${user.medicalCouncilCode??"بدون کد"}`:`Physician · ${user.medicalCouncilCode??"no code"}`):(fa?"دستیار / پرستار":"Assistant / nurse")}</small></div></div><div className={styles.meta}><small>{user.email??user.mobile??"—"}</small><small>{user.practiceName??"—"}</small></div><div className={styles.badges}><span className={styles.badge} data-tone={user.status==="active"?"success":"danger"}>{user.status==="active"?(fa?"فعال":"Active"):(fa?"غیرفعال":"Disabled")}</span><span className={styles.badge} data-tone={user.passwordSet?"success":"warning"}>{user.passwordSet?(fa?"رمز تعریف شده":"Password set"):(fa?"بدون رمز":"No password")}</span></div><div className={styles.actions}><button disabled={busy} onClick={()=>setResetUser(user)}>{fa?"تعویض رمز":"Reset password"}</button><button className={user.status==="active"?styles.disable:undefined} disabled={busy} onClick={()=>void toggleStatus(user)}>{user.status==="active"?(fa?"محدود کردن":"Deactivate"):(fa?"فعال‌سازی":"Reactivate")}</button></div></article>)}</section>
   {resetUser&&<section className={styles.reset}><h2>{fa?`تعویض رمز ${resetUser.firstName} ${resetUser.lastName}`:`Reset password for ${resetUser.firstName} ${resetUser.lastName}`}</h2><p>{fa?"رمز جدید حداقل ۱۰ کاراکتر باشد. پس از تغییر، نشست‌های قبلی کاربر باید باطل شوند.":"Use at least 10 characters. Existing sessions should be revoked after the reset."}</p><div className={styles.resetGrid}><input type="password" autoComplete="new-password" placeholder={fa?"رمز جدید":"New password"} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><input type="password" autoComplete="new-password" placeholder={fa?"تکرار رمز":"Confirm password"} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/><button disabled={busy||newPassword.length<10||newPassword!==confirmPassword} onClick={()=>void reset()}>{fa?"ثبت رمز جدید":"Save new password"}</button></div></section>}
  </>}
  {(status||error)&&<p className={`${styles.status} ${error?styles.error:""}`} role={error?"alert":"status"}>{error||status}</p>}
 </main>;
}
