import type { ClinicalDomainCapability } from "./types.js";

export const metabolicClinicalDomainCapabilities = [
  {
    domain: "liver",
    executionState: "partially_executable",
    decisionGraphLanes: ["liver"],
    executableObjectives: ["liver_directed_therapy"],
    minimumSafeInputs: ["MASLD/MASH confirmation", "fibrosis stage", "cirrhosis/decompensation", "weight for resmetirom", "product-specific interaction/contraindication screening", "current medication reconciliation"],
    inputContract: {
      core: ["liver.masld_mash", "liver.fibrosis_stage", "liver.cirrhosis", "liver.decompensated_cirrhosis"],
      conditional: [
        "core.age_years",
        "anthropometrics.weight_kg",
        "safety.product_specific_screen",
        "core.current_medications",
        "current_medication.interval_stage_reconciliation",
      ],
    },
    evidenceAuthorities: ["EASL-EASD-EASO MASLD 2024", "AASLD resmetirom 2024", "REZDIFFRA current regulatory label", "AASLD semaglutide MASH 2025", "WEGOVY current regulatory label"],
    boundary: "The liver lane executes only explicitly protocolized products and phenotypes: reviewed resmetirom plus product-bound WEGOVY initiation and interval-aware continuation for adult noncirrhotic F2-F3 MASH. Phase-aware non-insured treatment cost is implemented; other liver medicines remain review-only.",
    nextGap: "Populate the reviewed payer-scoped claim-timing registry from authoritative insurer evidence before treating insured-only phase-aware cost as executable; ordinary financial coverage rows must not infer claim timing.",
  },
  {
    domain: "obesity",
    executionState: "partially_executable",
    decisionGraphLanes: ["glycemic"],
    executableObjectives: ["weight_benefit"],
    minimumSafeInputs: ["BMI/weight", "Type 2 treatment context", "product-specific contraindications"],
    inputContract: {
      core: ["anthropometrics.weight_kg", "anthropometrics.bmi"],
      conditional: ["core.current_medications", "safety.product_specific_screen"],
    },
    evidenceAuthorities: ["ADA 2026 Section 9", "reviewed GLP-1/GIP-GLP-1 product labels"],
    boundary: "Weight is an explicit Type 2 preference axis; a standalone obesity-prescribing engine is not implied.",
    nextGap: "Keep obesity execution inside reviewed Type 2 indications until a separate obesity module is explicitly scoped.",
  },
  {
    domain: "hypertension",
    executionState: "executable",
    decisionGraphLanes: ["hypertension"],
    executableObjectives: ["blood_pressure_control"],
    minimumSafeInputs: ["treatment-range BP", "established hypertension-treatment context", "represented RAAS indication", "renal/potassium facts as product requires"],
    inputContract: {
      core: ["cardiovascular.systolic_bp", "cardiovascular.diastolic_bp", "hypertension.established_treatment_context"],
      conditional: ["kidney.egfr", "kidney.potassium"],
    },
    evidenceAuthorities: ["ADA 2026 Section 10", "ACC/AHA Hypertension 2025", "ACEi/ARB product labels"],
    boundary: "A single encounter BP does not create a hypertension diagnosis or autonomous initiation.",
  },
  {
    domain: "lipids",
    executionState: "executable",
    decisionGraphLanes: ["lipids"],
    executableObjectives: ["lipid_risk_reduction"],
    minimumSafeInputs: ["age", "ASCVD status", "CrCl for renal-specific statin branch when required", "pregnancy context"],
    inputContract: {
      core: ["core.age_years", "cardiovascular.ascvd"],
      conditional: ["kidney.creatinine_clearance", "core.pregnancy"],
    },
    evidenceAuthorities: ["ADA 2026 Section 10", "ACC/AHA Dyslipidemia 2026", "statin product labels"],
    boundary: "Statin indication and product dose are separate; unsupported nonstatin classes remain review-only.",
  },
  {
    domain: "heart_failure",
    executionState: "executable",
    decisionGraphLanes: ["heart_failure"],
    executableObjectives: ["heart_failure_protection"],
    minimumSafeInputs: ["heart-failure phenotype", "LVEF for HFrEF-specific MRA", "eGFR", "potassium"],
    inputContract: {
      core: ["cardiovascular.heart_failure"],
      conditional: ["cardiovascular.lvef_percent", "cardiovascular.nyha_class", "cardiovascular.systolic_bp", "kidney.egfr", "kidney.potassium"],
    },
    evidenceAuthorities: ["AHA/ACC/HFSA 2022", "ACC HFrEF 2024", "ADA 2026 Section 10", "product regulatory labels"],
    boundary: "Current dedicated MRA execution is HFrEF-specific; heartFailure=true alone is not sufficient for spironolactone.",
  },
  {
    domain: "ascvd",
    executionState: "executable",
    decisionGraphLanes: ["ascvd", "lipids"],
    executableObjectives: ["ascvd_protection", "lipid_risk_reduction"],
    minimumSafeInputs: ["established ASCVD phenotype", "relevant medication safety facts"],
    inputContract: {
      core: ["cardiovascular.ascvd"],
      conditional: ["core.current_medications", "safety.product_specific_screen"],
    },
    evidenceAuthorities: ["ADA 2026 Sections 9 and 10", "ESC Diabetes-CVD 2023", "ACC/AHA Dyslipidemia 2026"],
    boundary: "ASCVD creates independent organ-protection and lipid objectives; unsupported adjunct classes remain review-only until protocolized.",
  },
  {
    domain: "masld_mash",
    executionState: "partially_executable",
    decisionGraphLanes: ["liver"],
    executableObjectives: ["liver_directed_therapy"],
    minimumSafeInputs: ["adult status", "confirmed MASH", "F2/F3 fibrosis", "explicit noncirrhotic state", "actual body weight when resmetirom is considered", "WEGOVY MTC/MEN2/hypersensitivity/gastroparesis/pancreatitis screen", "current GLP-1/semaglutide reconciliation"],
    inputContract: {
      core: ["core.age_years", "liver.masld_mash", "liver.fibrosis_stage", "liver.cirrhosis", "liver.decompensated_cirrhosis"],
      conditional: [
        "anthropometrics.weight_kg",
        "safety.product_specific_screen",
        "core.current_medications",
        "current_medication.interval_stage_reconciliation",
      ],
    },
    evidenceAuthorities: ["EASL-EASD-EASO MASLD 2024", "AASLD resmetirom 2024", "REZDIFFRA current regulatory label", "AASLD semaglutide MASH 2025", "WEGOVY current regulatory label"],
    boundary: "Resmetirom and product-bound WEGOVY initiation/continuation are executable only for the reviewed adult F2-F3 noncirrhotic phenotype after product-specific safety, exact weekly interval/stage reconciliation, and Iran-market gates pass. Future escalation cost remains conditional/display-only until the future stage is observed; other MASH medicines remain review-only.",
    nextGap: "Populate the reviewed payer-scoped claim-timing registry from authoritative insurer evidence before treating insured-only phase-aware cost as executable; ordinary financial coverage rows must not infer claim timing.",
  },
] as const satisfies readonly ClinicalDomainCapability[];
