import type { ClinicalEvidenceSource } from "./guideline-registry.js";

/**
 * Reviewed multidomain evidence sources that complement the original Type 2
 * glycemic registry. They are registered for provenance/monitoring only here;
 * source registration never activates a medication rank, hard gate, or dose.
 * Executable effects require separately reviewed rule-pack / Decision Graph
 * code and, where dosing is involved, an exact product/regulatory label.
 */
export const multidomainGuidelineSources = [
  {
    id: "ada-cvd-2026",
    shortCode: "ADA10-2026",
    publisher: "ADA",
    title: "Standards of Care in Diabetes—2026, Section 10: Cardiovascular Disease and Risk Management",
    sourceKind: "guideline",
    sourceUrl: "https://diabetesjournals.org/care/article/49/Supplement_1/S216/163933/10-Cardiovascular-Disease-and-Risk-Management",
    activeVersion: "Standards of Care in Diabetes—2026 / Section 10",
    publishedAt: "2025-12-08",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["hypertension", "lipids", "ascvd", "heart_failure", "ace_inhibitor", "arb", "statin", "mra", "cardiorenal"],
    engineRoleFa: "اهداف فشارخون و چربی، انتخاب ACEi/ARB در دیابت و کاهش ریسک قلبی‌عروقی؛ دوز دقیق همچنان از label رگولاتوری می‌آید",
    engineRoleEn: "Blood-pressure/lipid goals, ACEi/ARB selection in diabetes, and cardiovascular risk reduction; exact dose remains label-derived",
  },
  {
    id: "ada-ckd-2026",
    shortCode: "ADA11-2026",
    publisher: "ADA",
    title: "Standards of Care in Diabetes—2026, Section 11: Chronic Kidney Disease and Risk Management",
    sourceKind: "guideline",
    sourceUrl: "https://diabetesjournals.org/care/article/49/Supplement_1/S246/163914/11-Chronic-Kidney-Disease-and-Risk-Management",
    activeVersion: "Standards of Care in Diabetes—2026 / Section 11",
    publishedAt: "2025-12-08",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["ckd", "albuminuria", "ras_blockade", "finerenone", "mra", "sglt2", "glp1", "potassium_monitoring"],
    engineRoleFa: "RAS blockade، finerenone/nsMRA، SGLT2/GLP-1 و پایش پتاسیم در دیابت همراه CKD",
    engineRoleEn: "RAS blockade, finerenone/nsMRA, SGLT2/GLP-1, and potassium monitoring in diabetes with CKD",
  },
  {
    id: "ada-microvascular-2026",
    shortCode: "ADA12-2026",
    publisher: "ADA",
    title: "Standards of Care in Diabetes—2026, Section 12: Retinopathy, Neuropathy, and Foot Care",
    sourceKind: "guideline",
    sourceUrl: "https://diabetesjournals.org/care/article/49/Supplement_1/S261/163919/12-Retinopathy-Neuropathy-and-Foot-Care-Standards",
    activeVersion: "Standards of Care in Diabetes—2026 / Section 12",
    publishedAt: "2025-12-08",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["retinopathy", "macular_edema", "neuropathy", "neuropathic_pain", "diabetic_foot"],
    engineRoleFa: "مرور درمان‌های رتینوپاتی/ادم ماکولا، نوروپاتی دردناک و مراقبت پای دیابتی",
    engineRoleEn: "Retinopathy/macular-edema therapy, painful neuropathy treatment, and diabetic-foot care",
  },
  {
    id: "ada-pregnancy-2026",
    shortCode: "ADA15-2026",
    publisher: "ADA",
    title: "Standards of Care in Diabetes—2026, Section 15: Management of Diabetes in Pregnancy",
    sourceKind: "guideline",
    sourceUrl: "https://diabetesjournals.org/care/article/49/Supplement_1/S321/163918/15-Management-of-Diabetes-in-Pregnancy-Standards",
    activeVersion: "Standards of Care in Diabetes—2026 / Section 15",
    publishedAt: "2025-12-08",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["pregnancy", "insulin", "medication_safety", "hypertension", "ckd", "retinopathy"],
    engineRoleFa: "ایمنی دارویی و مسیر ترجیحی انسولین در بارداری همراه دیابت و مرور داروهای نامناسب بارداری",
    engineRoleEn: "Medication safety and insulin-preferred pathways in pregnancy complicated by diabetes",
  },
  {
    id: "acc-aha-htn-2025",
    shortCode: "ACC/AHA-HTN 2025",
    publisher: "ACC/AHA",
    title: "2025 High Blood Pressure Guideline",
    sourceKind: "guideline",
    sourceUrl: "https://professional.heart.org/en/science-news/2025-high-blood-pressure-guideline",
    activeVersion: "2025 ACC/AHA High Blood Pressure Guideline",
    publishedAt: "2025-08-14",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["hypertension", "blood_pressure_target", "ckd", "diabetes", "resistant_hypertension", "combination_therapy"],
    engineRoleFa: "اهداف فشارخون، زمان شروع درمان و استراتژی تک‌دارویی/ترکیبی در بزرگسالان از جمله دیابت و CKD",
    engineRoleEn: "Blood-pressure targets, treatment thresholds, and single/combination therapy strategy including diabetes and CKD",
  },
  {
    id: "acc-aha-dyslipidemia-2026",
    shortCode: "ACC/AHA-LIPID 2026",
    publisher: "ACC/AHA",
    title: "2026 Guideline on the Management of Dyslipidemia",
    sourceKind: "guideline",
    sourceUrl: "https://professional.heart.org/en/science-news/2026-guideline-on-the-management-of-dyslipidemia",
    activeVersion: "2026 ACC/AHA Dyslipidemia Guideline",
    publishedAt: "2026-03-13",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["lipids", "ldl", "statin", "nonstatin", "ascvd", "hypertriglyceridemia", "lpa", "apob"],
    engineRoleFa: "شدت درمان کاهنده چربی و اهداف LDL/non-HDL بر اساس ریسک؛ جایگزین guideline کلسترول 2018",
    engineRoleEn: "Risk-based lipid-lowering intensity and LDL/non-HDL goals; replaces the 2018 cholesterol guideline",
  },
  {
    id: "aha-acc-hfsa-hf-2022",
    shortCode: "AHA/ACC/HFSA-HF 2022",
    publisher: "AHA/ACC/HFSA",
    title: "2022 AHA/ACC/HFSA Guideline for the Management of Heart Failure",
    sourceKind: "guideline",
    sourceUrl: "https://professional.heart.org/en/science-news/2022-guideline-for-the-management-of-heart-failure",
    activeVersion: "2022 AHA/ACC/HFSA Heart Failure Guideline",
    publishedAt: "2022-04-01",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["heart_failure", "hfref", "hfmref", "hfpef", "mra", "spironolactone", "sglt2", "raas"],
    engineRoleFa: "GDMT نارسایی قلبی و eligibility/safety کلاس MRA از جمله spironolactone؛ اجرای دوز product-specific جداست",
    engineRoleEn: "Heart-failure GDMT and MRA eligibility/safety including spironolactone; product-specific dosing remains separate",
  },
  {
    id: "acc-hfref-2024",
    shortCode: "ACC-HFrEF 2024",
    publisher: "ACC",
    title: "2024 ACC Expert Consensus Decision Pathway for Treatment of Heart Failure With Reduced Ejection Fraction",
    sourceKind: "consensus",
    sourceUrl: "https://www.acc.org/Guidelines/Guidelines/2024/03/08/15/40/Treatment-of-Heart-Failure-With-Reduced-Ejection-Fraction-ECDP",
    activeVersion: "ACC HFrEF Expert Consensus Decision Pathway 2024",
    publishedAt: "2024-03-08",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["heart_failure", "hfref", "gdmt", "arni", "beta_blocker", "sglt2", "mra", "titration"],
    engineRoleFa: "ترتیب عملی شروع/افزودن/تیتراسیون اجزای GDMT در HFrEF؛ مکمل guideline اصلی 2022",
    engineRoleEn: "Practical initiation/addition/titration of HFrEF GDMT, complementing the 2022 guideline",
  },
  {
    id: "aasld-resmetirom-2024",
    shortCode: "AASLD-RESMETIROM 2024",
    publisher: "AASLD",
    title: "Resmetirom Therapy for Metabolic Dysfunction-Associated Steatotic Liver Disease — Update to AASLD Practice Guidance",
    sourceKind: "consensus",
    sourceUrl: "https://www.aasld.org/practice-guidelines/clinical-assessment-and-management-metabolic-dysfunction-associated-steatotic",
    activeVersion: "AASLD MASLD Practice Guidance — Resmetirom update, October 2024",
    publishedAt: "2024-10",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["masld_mash", "fibrosis", "resmetirom", "patient_selection", "monitoring"],
    engineRoleFa: "معیارهای عملی انتخاب بیمار و پایش resmetirom در MASLD/MASH؛ در کنار EASL و منبع رگولاتوری",
    engineRoleEn: "Practical patient selection and monitoring for resmetirom in MASLD/MASH alongside EASL and regulatory evidence",
  },
  {
    id: "US-LABEL-REZDIFFRA-2026-07",
    shortCode: "REZDIFFRA PI 2026-07",
    publisher: "DailyMed / FDA label",
    title: "REZDIFFRA (resmetirom) tablets — U.S. prescribing information",
    sourceKind: "regulatory",
    sourceUrl: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e67ea09f-a840-439c-86c8-f98585f978b2",
    activeVersion: "DailyMed updated 2026-07-31",
    publishedAt: "2026-07-31",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["masld_mash", "fibrosis_f2_f3", "resmetirom", "weight_tiered_dose", "cyp2c8", "statin_interaction", "monitoring"],
    engineRoleFa: "دوز دقیق resmetirom بر اساس وزن، تعدیل با مهارکننده متوسط CYP2C8، محدودیت تداخل statin و مرز noncirrhotic F2-F3",
    engineRoleEn: "Exact resmetirom weight-tiered dosing, moderate-CYP2C8 dose modification, statin interaction limits, and the noncirrhotic F2-F3 boundary",
    lastCheckedAt: "2026-09-05",
  },
  {
    id: "aasld-semaglutide-mash-2025",
    shortCode: "AASLD-SEMA-MASH 2025",
    publisher: "AASLD",
    title: "Semaglutide Therapy for Metabolic Dysfunction-Associated Steatohepatitis — Update to AASLD Practice Guidance",
    sourceKind: "consensus",
    sourceUrl: "https://www.aasld.org/aasld-announces-update-metabolic-dysfunction-associated-steatotic-liver-disease-masld-practice",
    activeVersion: "AASLD MASLD Practice Guidance — Semaglutide update, November 2025",
    publishedAt: "2025-11-07",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["masld_mash", "fibrosis_f2_f3", "semaglutide", "obesity", "type2_diabetes", "monitoring"],
    engineRoleFa: "معیارهای انتخاب بیمار، مدیریت همبودها و پایش semaglutide در MASH با فیبروز متوسط تا پیشرفته",
    engineRoleEn: "Patient selection, comorbidity management, and semaglutide monitoring in MASH with moderate-to-advanced fibrosis",
  },
  {
    id: "US-LABEL-WEGOVY-2026-06",
    shortCode: "WEGOVY PI 2026-06",
    publisher: "DailyMed / FDA label",
    title: "WEGOVY (semaglutide) injection/tablets — U.S. prescribing information",
    sourceKind: "regulatory",
    sourceUrl: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ee06186f-2aa3-4990-a760-757579d8f77b",
    activeVersion: "DailyMed effective 2026-06-18 / SPL version 19",
    publishedAt: "2026-06-18",
    monitored: true,
    engineInfluence: true,
    engineDomains: ["masld_mash", "fibrosis_f2_f3", "semaglutide", "wegovy", "dose_escalation", "glp1_safety", "monitoring"],
    engineRoleFa: "اندیکاسیون و دوز محصولی WEGOVY برای MASH غیرسیروتیک F2-F3، escalation هفتگی و contraindication/warningهای اختصاصی label",
    engineRoleEn: "Product-specific WEGOVY indication and dosing for noncirrhotic F2-F3 MASH, weekly escalation, and label-specific contraindication/warning boundaries",
    lastCheckedAt: "2026-09-05",
  },
] satisfies ClinicalEvidenceSource[];
